import { withTRPC } from "@trpc/next";
import type { AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import superjson from "superjson";
import { AppRouter } from "../server/infrastructure/trpc";
import NavBar from "../ui/Navbar";
import "../ui/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
	return (
	<>
		<Head>
			<title>minis colors app</title>
			<meta name="description" content="Generated by create-t3-app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<NavBar/>
		<main>
			<Component {...pageProps} />
		</main>
	</>);
};

const getBaseUrl = () => {
	if (typeof window !== "undefined") return "";
	if (process.browser) return "";
	if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;

	return `http://localhost:${process.env.PORT ?? 3000}`;
};

export default withTRPC<AppRouter>({
	config: ({}) => ({
		url: `${getBaseUrl()}/api/trpc`,
		transformer: superjson,
	}),
	ssr: false,
})(MyApp);
