version: '3.4'

services:
  
  dailytrends.web:
    container_name: miniscolorsapp.web
    depends_on:
      - miniscolorsapp.api
    ports:
      - "4200:80"
  
  dailytrends.api:
    container_name: miniscolorsapp.api
    depends_on: 
    - miniscolorsapp.db
    ports:
      - "8080:8080"
    environment:
      - MONGODB=mongodb://miniscolorsapp.db:27017//MinisColorAppDB
      - API_PORT=8080
      - UPDATE_ALL_FEEDS_CRON_TIME_JOB=00 00 6 * * *
  
  dailytrends.db:
    container_name: dailytrends.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db